services:
  app:
    restart: always
    container_name: go-server
    tty: true
    build: .
    volumes:
      - .:/app
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - server-database

  postgresdb:
    restart: always
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DBNAME}
    ports:
      - "${DB_PORT}:${DB_INSIDE_PORT}"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME} -d ${DB_DBNAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - server-database
      - database

  migrate:
    image: migrate/migrate
    depends_on:
      postgresdb:
        condition: service_healthy
    command: "-path /migrations/migrations -database=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_INSIDE_PORT}/${DB_DBNAME}?sslmode=${DB_SSLMODE} up"
    volumes:
      - ./migrations:/migrations
    links:
      - postgresdb
    networks:
      - database

networks:
  server-database:
    driver: bridge
  database:
    driver: bridge
